# -*- coding: utf-8 -*-
#    ____  ____  ______       __      __       __       _____
#   / __ )/ __ \/ ___/ |     / /___ _/ /______/ /_     |__  /
#  / __  / / / /\__ \| | /| / / __ `/ __/ ___/ __ \     /_ <
# / /_/ / /_/ /___/ /| |/ |/ / /_/ / /_/ /__/ / / /   ___/ /
#/_____/\____//____/ |__/|__/\__,_/\__/\___/_/ /_/   /____/
#                German BOS Information Script
#                     by Bastian Schroll

server:
  port: 8080
  name: BW3 Server        # name of the BW3 Server instance
  useBroadcast: no        # serve server ip on broadcast request

alarmRouter:
- Router 1
router:
- name: Router 1
  route:
# Filters
  - type: module
    name: Filter FMS/ZVEI
    res: filter.modeFilter
    config:
      allowed:
        - fms
        - zvei

# Descriptor
  - type: module
    name: Klartext
    res: descriptor
    config:
      - scanField: zvei
        descrField: description
        wildcard: "{DESCR}"
        descriptions:
          - for: 21017
            add: Test 21017
          - for: 21232
            add: Test 21232
          - for: 21208
            add: Test 21208
 
# Telegram Plugin
  - type: plugin
    name: Telegram Plugin
    res: telegram
    config:
      message: "{TIME};     {FREQ}\n{TONE}: {DESCR}"
      botToken: "*hier-kommt-das-tocken-mit-passwort-rein*"
      chatIds:
        - "*CHATID*"
